In [1]:
import QAData
from os import listdir
from os.path import isfile, join
import PassageRetrieval as pr
from json2html import *
import matplotlib
#matplotlib.use('Agg')
import pylab as plt
import nlp_utils
import time
import os
import json
import logging
from json_utils import JSONConnector
from QAData import DataSetFactory
import models
logger = logging.getLogger()
logger.setLevel(logging.INFO)

Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 5103)


In [2]:
w2v_path = '/home/aerossom/datasets/word2vect/GoogleNews-vectors-negative300.bin'
w2v_util = nlp_utils.Word2vectUtils(w2v_path)

In [113]:
ds = DataSetFactory.loadDataSet('WikiQADataSet')
qa_pair = {}
qa_pair['train'] = ds.build_qa_pairs(ds.questions['train'])
qa_pair['validate'] = ds.build_qa_pairs(ds.questions['validate'])
qa_pair['test'] = ds.build_qa_pairs(ds.questions['test'])

shapes:  (100, 100) (8, 39)
[u'when', u'does', u'black', u'friday', u'start', u'for', u'christmas'] [u'in', u'2012', u'walmart', u'and', u'several', u'other', u'retailers', u'announced', u'that', u'they', u'would', u'open', u'most', u'of', u'their', u'stores', u'at', u'8', u'00', u'p', u'm', u'on', u'thanksgiving', u'day', u'except', u'in', u'states', u'where', u'opening', u'on', u'thanksgiving', u'is', u'prohibited', u'due', u'to', u'blue', u'laws', u'such', u'as', u'massachusetts', u'where', u'they', u'still', u'opened', u'around', u'midnight', u'prompting', u'calls', u'for', u'a', u'walkout', u'among', u'some', u'workers']
shapes:  (100, 100) (7, 50)
[u'who', u'are', u'the', u'stakeholders', u'in', u'a', u'change', u'process'] [u'stakeholder', u'corporate', u'a', u'person', u'group', u'organization', u'member', u'or', u'system', u'who', u'affects', u'or', u'can', u'be', u'affected', u'by', u'an', u'organization', u's', u'actions']
shapes:  (100, 100) (8, 20)
[u'when', u'was', u'stev

In [114]:
import KerasConvNetModel_3
reload(KerasConvNetModel_3)
js = JSONConnector('/home/aerossom/passage-retrieval/conf_experiments/KerasConvNetModel_3_exp_1.json')
model_params = {"w2v": w2v_util, "runid":'test_run',  "params":js.data }
p_model = models.PassRtvModelFactory.load_model('KerasConvNetModel_3','KerasConvNetModel_3',model_params)
history = p_model.train(ds, qa_pair)

th
Epoch 1/500
x_shape:  (128, 2, 100, 100)
x_shape:  (64, 2, 100, 100)
Epoch 00000: val_acc improved from -inf to 0.45312, saving model to /home/aerossom/passage-retrieval/experiments/working_files/keras_convnet_test_run_best.hdf5
128/128 [==============================] - 9s - loss: 0.2512 - acc: 0.5000 - val_loss: 0.2512 - val_acc: 0.4531
Epoch 2/500
x_shape:  (64, 2, 100, 100)
x_shape:  (128, 2, 100, 100)
x_shape:  (64, 2, 100, 100)
Epoch 00001: val_acc did not improve
128/128 [==============================] - 12s - loss: 0.2513 - acc: 0.5312 - val_loss: 0.2512 - val_acc: 0.4531
Epoch 3/500
x_shape:  (64, 2, 100, 100)
x_shape:  (128, 2, 100, 100)
x_shape:  (64, 2, 100, 100)
Epoch 00002: val_acc did not improve
128/128 [==============================] - 11s - loss: 0.2517 - acc: 0.5312 - val_loss: 0.2512 - val_acc: 0.4375
Epoch 4/500
x_shape:  (64, 2, 100, 100)
x_shape:  (128, 2, 100, 100)
x_shape:  (64, 2, 100, 100)
Epoch 00003: val_acc did not improve
128/128 [===================

KeyboardInterrupt: 

th
Epoch 1/500
[[ 0.5  0.5  0.  ...,  0.   0.   0. ]
 [ 1.   1.   0.5 ...,  0.5  0.5  0.5]
 [ 0.5  0.5  0.  ...,  0.   0.   0. ]
 ..., 
 [ 0.5  0.5  0.  ...,  0.   0.   0. ]
 [ 0.5  0.5  0.  ...,  0.   0.   0. ]
 [ 0.5  0.5  0.  ...,  0.   0.   0. ]]


Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/keras/engine/training.py", line 425, in data_generator_task
    generator_output = next(generator)
  File "models.py", line 57, in next
    return self.it.next()
  File "KerasConvNetModel_3.py", line 108, in generateXYBatches
    x, y = self.buildCosineSimMatrix(samples,max_terms=self.max_words)
  File "KerasConvNetModel_3.py", line 81, in buildCosineSimMatrix
    x.append( np.stack( (cos_matrix, sal_matrix), axis=0) )
  File "/home/aerossom/.conda/envs/py2/lib/python2.7/site-packages/numpy/core/shape_base.py", line 339, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all i

Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None

In [121]:
a = np.random.rand(1, 7, 7)
b = np.random.rand(1, 7, 7)
#np.concatenate?

In [123]:
c = np.random.rand(7, 7)

In [128]:
print c[0:4,0:4]

[[ 0.09057859  0.89230215  0.6376833   0.24524274]
 [ 0.49635115  0.22892506  0.09040055  0.52361496]
 [ 0.83178142  0.78818013  0.05342592  0.50451976]
 [ 0.06595992  0.78940282  0.46743575  0.34616667]]


In [126]:
c.reshape((2,2))

ValueError: total size of new array must be unchanged

In [145]:
np.stack((a,b), axis=-1).shape

(128, 40, 40, 2)

In [68]:
js = JSONConnector('/home/aerossom/passage-retrieval/conf_experiments/KerasConvNetModel_exp_1.json')

In [115]:
a

NameError: name 'a' is not defined

x_shape:  (128, 2, 100, 100)


In [106]:
from nltk.tag import pos_tag, map_tag

print nltk.pos_tag(['Colombia'])[0][1]
tagged_sent = nltk.pos_tag(['Where','What','who'])

simplifiedTags = [(word, map_tag('en-ptb', 'universal', tag)) for word, tag in tagged_sent]
print(simplifiedTags)
print nltk.pos_tag(['Where','What','who','ice','how'])

NNP
[('Where', u'ADV'), ('What', u'PRON'), ('who', u'PRON')]
[('Where', 'WRB'), ('What', 'WP'), ('who', 'WP'), ('ice', 'NN'), ('how', 'WRB')]


In [94]:
import nltk
import numpy as np
def getSalienceScore(qv, av, maxterms=40):
    score = 0
    imp_postag = set(['WRB','VB', 'VBD', 'VBG', 'VBN', 'VBP','VBZ', 'WDT', 'WP', 'WRB', 'NN', 'NNS', 'NNP', 'NNPS', 'MD'])
    pw1 = nltk.pos_tag(qv)
    pw2 = nltk.pos_tag(av)
    w1_m = np.zeros((maxterms,maxterms))
    w2_m = np.zeros((maxterms,maxterms))
    pw1_l = [len(set([w1[1]]).intersection(imp_postag)) for w1 in pw1]
    w1_m[:,0:len(pw1_l)]=pw1_l
    pw2_l = [len(set([w2[1]]).intersection(imp_postag)) for w2 in pw2]
    w2_m[:,0:len(pw2_l)]=pw2_l
    out_m = (w1_m + w2_m.T)/2
    #print pw1_l, pw2_l, pw1
    print out_m
    #print w1_m

In [95]:
getSalienceScore(['the', 'car', 'is', 'blue'],['what', 'is', 'the', 'color'], 6)

[0, 1, 1, 0] [1, 1, 0, 1] [('the', 'DT'), ('car', 'NN'), ('is', 'VBZ'), ('blue', 'JJ')]
[[ 0.5  1.   1.   0.5  0.5  0.5]
 [ 0.5  1.   1.   0.5  0.5  0.5]
 [ 0.   0.5  0.5  0.   0.   0. ]
 [ 0.5  1.   1.   0.5  0.5  0.5]
 [ 0.   0.5  0.5  0.   0.   0. ]
 [ 0.   0.5  0.5  0.   0.   0. ]]


In [119]:
def buildCosineSimMatrix(questions_answer_pairs, max_terms=20):
        #Construct Question Answer Matrix Pairs
        x = []
        y = []
        for pair in questions_answer_pairs:
            q_list = nlp_utils.data_preprocess(pair.q)
            q_vect = w2vutil.transform2Word2Vect(q_list)
            #print q
            cos_matrix = []
            sal_matrix = []
            for i, q_i in enumerate(q_vect):
                if i==max_terms:
                    break
                sim_qi_a = []
                salience_qi_a = []
                a_list = nlp_utils.data_preprocess(pair.a)
                a_vect = w2vutil.transform2Word2Vect(a_list)
                for k, a_k in enumerate(a_vect):
                    if k==max_terms:
                        break
                    #print a_k
                    sim_qi_a += [spatial.distance.cosine(q_i, a_k)]
                    salience_qi_a += [getSalienceScore(q_list[i], a_list[k])]
                    #print q_list[i], a_list[k], getSalienceScore(q_list[i], a_list[k])
                cos_matrix += [sim_qi_a]
                sal_matrix += [salience_qi_a]
            cos_matrix = np.array(cos_matrix)
            sal_matrix = np.array(sal_matrix)
            shape_cos_matrix = cos_matrix.shape
            cos_matrix = np.pad(cos_matrix, ((0,max_terms-shape_cos_matrix[0]),(0,max_terms-shape_cos_matrix[1])), mode='constant')
            sal_matrix = np.pad(sal_matrix, ((0,max_terms-shape_cos_matrix[0]),(0,max_terms-shape_cos_matrix[1])), mode='constant')
            if np.isnan(cos_matrix).any():
                print 'ERROR IS NAN: ',pair
            x.append( [np.expand_dims(cos_matrix,0), np.expand_dims(sal_matrix,0)] )
            y.append( pair.l )
            print x
        return x, y

In [120]:
reload(nlp_utils)
from scipy import spatial
import numpy as np
w2vutil=w2v_util
t = buildCosineSimMatrix(qa_pair['train'][0:4])

[[array([[[ 1.01891454,  0.86096887,  0.94080197,  0.95078528,  0.9289416 ,
          0.82346678,  1.07376913,  0.90710939,  0.95078528,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.89081848,  0.85335034,  1.03150204,  0.96907873,  0.93171173,
          0.8700887 ,  0.9728588 ,  1.0112373 ,  0.96907873,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.95561202,  0.87433413,  0.74425039,  0.        ,  0.56481206,
          1.02786626,  0.96170719,  0.92025658,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.04975737,  0.92717969,  0.77764095,  0.59880871,  0.19139028,
          1.02454226,  1.04411818

In [ ]:
t